name: unread_frontend
description: Unread Frontend Monorepo - An ebook sharing platform
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dev_dependencies:
  melos: ^6.3.3 