name: unread_mobile
description: Unread mobile application - An ebook sharing platform that connects authors and readers
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Shared packages
  app_ui:
    path: ../../packages/app_ui
  authentication:
    path: ../../packages/authentication
  common:
    path: ../../packages/common
  design_ui:
    path: ../../packages/design_ui

  # Core dependencies
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.0
  go_router: ^15.1.2
  dio: ^5.7.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  
  # UI and UX
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.7
  flutter_gen: ^5.8.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:

  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.0
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true