name: common
description: Shared business logic and models for Unread applications
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  envied: ^1.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.0
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  envied_generator: ^1.1.1
