name: design_ui
description: Shared UI components for Unread applications
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0

  app_ui:
    path: ../app_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0
