name: app_ui
description: Shared assets, themes, and UI constants for Unread applications
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  flutter_svg: ^2.1.0
  flutter_gen_core: ^5.8.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.24.0
  flutter_gen_runner: ^5.8.0
  spider: ^4.2.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/books/
    - assets/images/books/generated/
    - assets/animations/lottie/

